### ISSUE TITLE
panic with: fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by ijc** [linuxkit/rtf#23]
Seen in https://linuxkit.datakit.ci/log/saved/linuxkit-build-of-c6b7b3c00af3e8619b15d43be52c53c9e8db5a46-default-ci-pr/1b0a95c509e2145e4a0550902ca71535517c00d7 which was testing https://github.com/linuxkit/linuxkit/pull/2224 (a docs only change).

**Comment by dave-tucker** [comment]
@ijc thanks! I've got a PR ready to fix this. Will push it in a moment...
